### ISSUE TITLE
Feedback from Robb

### ISSUE THREAD

**Issue by sphillips** [CareerFoundry/rails-vm#1]
- instructions use rbenv but course uses rvm
- is IP binding necessary? (need to test on windows machine)

note on tone and audience:
The Readme doc assumes a decent level of knowledge about working with files, Windows, and some other things. It’ll serve as a barrier to entry to many. Personally, I think this is a good thing because it’ll filter out students who wouldn’t be able to manage it. That may not be your intent, of course

**Comment by simonbacquie** [comment]
The rbenv vs. rvm issue is addressed in this PR: https://github.com/CareerFoundry/rails-vm/pull/2

**Comment by slaveunit** [comment]
Hello-hello.

I'm using Windows > Virtual Machine > Vagrant.  All is well with the first app I made.  But when I try to make another box for a second one, I can't start the local server because I get stuck at `/vagrant$ bundle`.

I'm new at this.  Please bear with me.

Thanks!  :)

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ bundle
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies...
Rubygems 1.8.23 is not threadsafe, so your gems will be installed one at a time.
 Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.
Using rake 11.2.2
Using i18n 0.7.0
Installing json 1.8.3 with native extensions

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension
.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such
 file -- mkmf (LoadError)
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from extconf.rb:1:in `<main>'


Gem files will remain installed in /tmp/bundler20160620-1546-19u7ieejson-1.8.3/g
ems/json-1.8.3 for inspection.
Results logged to /tmp/bundler20160620-1546-19u7ieejson-1.8.3/gems/json-1.8.3/ex
t/json/ext/generator/gem_make.out
Using minitest 5.9.0
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using pkg-config 1.1.7
Using rack 1.6.4
Installing mime-types-data 3.2016.0521

Gem::InstallError: mime-types-data requires Ruby version >= 2.0.
Using arel 6.0.3
Using debug_inspector 0.0.2
Using bundler 1.12.5
Installing byebug 9.0.5 with native extensions

Gem::InstallError: byebug requires Ruby version >= 2.0.0.
Using coffee-script-source 1.10.0
Using execjs 2.7.0
Using thor 0.19.1
Using concurrent-ruby 1.0.2
Using multi_json 1.12.1
Using sass 3.4.22
Using tilt 2.0.5
Installing sqlite3 1.3.11 with native extensions

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension
.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such
 file -- mkmf (LoadError)
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from extconf.rb:3:in `<main>'


Gem files will remain installed in /tmp/bundler20160620-1546-ajacjysqlite3-1.3.1
1/gems/sqlite3-1.3.11 for inspection.
Results logged to /tmp/bundler20160620-1546-ajacjysqlite3-1.3.11/gems/sqlite3-1.
3.11/ext/sqlite3/gem_make.out
An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.
```
